import 'package:app/utils/Property.dart';

class CarModel {
  final Property car1;
  final Property car2;

  CarModel(this.car1, this.car2);
}

List<CarModel> datasList = [
  CarModel(
    Property(
       '1',
      'coupé',
      'Essence',
      'manuellle de 6 vitesses',
      '2019',
      '54000 kms',
      'jaune',
      'cuir noir',
      '5000 cm3',
      '8',
      '450 hp/450 ch',
      '36 cv fiscaux',
      '4 places',
      '2 portes',
      'images/car7.jpg',
      'Mercedes GL 450',
      'Annee 2019',
      'La Mercedes GLA 450 AMG 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
      'Munich',
      'Allemagne',
      '4000,000€',
      'Automatique',
    ),
    Property(
       '2',
      'coupé',
      'Essence',
      'manuellle de 6 vitesses',
      '2022',
      '54000 kms',
      'jaune',
      'cuir noir',
      '5000 cm3',
      '8',
      '450 hp/450 ch',
      '36 cv fiscaux',
      '4 places',
      '2 portes',
      'images/car8.jpg',
      'Mercedes Compressor',
      'Annee 2019',
      'La Mercedes GLA 450 AMG 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
      'Munich',
      'Allemagne',
      '32000,000€',
      'Automatique',
    )
      ),
  CarModel(
    Property(
       '5',
      'coupé',
      'Gazoil',
      'manuellle de 6 vitesses',
      '2019',
      '54000 kms',
      'jaune',
      'cuir noir',
      '5000 cm3',
      '8',
      '450 hp/450 ch',
      '36 cv fiscaux',
      '4 places',
      '2 portes',
      'images/car2.jpg',
      'Toyota Tundra',
      'Annee 2017',
      'La Mercedes GLA 450 AMG 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
      'Munich',
      'Allemagne',
      '4100,000€',
      'Automatique',
    ),
    Property(
       '6',
      'coupé',
      'Essence',
      'manuellle de 6 vitesses',
      '2022',
      '54000 kms',
      'jaune',
      'cuir noir',
      '5000 cm3',
      '8',
      '450 hp/450 ch',
      '36 cv fiscaux',
      '4 places',
      '2 portes',
      'images/car4.jpg',
      'Citroen C30',
      'Annee 2009',
      'La Mercedes GLA 450 AMG 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
      'Munich',
      'Allemagne',
      '32000,000€',
      'Automatique',
    )
     
  ),
  CarModel(
     Property(
       '3',
      'coupé',
      'Essence',
      'manuellle de 6 vitesses',
      '2019',
      '54000 kms',
      'jaune',
      'cuir noir',
      '5000 cm3',
      '8',
      '450 hp/450 ch',
      '36 cv fiscaux',
      '4 places',
      '2 portes',
      'images/car7.jpg',
      'Mercedes GL 450',
      'Annee 2019',
      'La Mercedes GLA 450 AMG 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
      'Munich',
      'Allemagne',
      '4000,000€',
      'Automatique',
    ),
    Property(
       '4',
      'coupé',
      'Essence',
      'manuellle de 6 vitesses',
      '2022',
      '54000 kms',
      'jaune',
      'cuir noir',
      '5000 cm3',
      '8',
      '450 hp/450 ch',
      '36 cv fiscaux',
      '4 places',
      '2 portes',
      'images/car8.jpg',
      'Mercedes Compressor',
      'Annee 2019',
      'La Mercedes GLA 450 AMG 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
      'Munich',
      'Allemagne',
      '32000,000€',
      'Automatique',
    )
  ),
];
