class Property {
  String id;
  String cat;
  String carb;
  String boit;
  String Mm;
  String Km;
  String col;
  String intr;
  String cyl;
  String nb;
  String puid;
  String puif;
  String plc;
  String por;
  List<String> image;
  String name;
  String year;
  String description;
  String town;
  String country;
  String price;
  String type;

  Property(
      this.id,
      this.cat,
      this.carb,
      this.boit,
      this.Mm,
      this.Km,
      this.col,
      this.intr,
      this.cyl,
      this.nb,
      this.puid,
      this.puif,
      this.plc,
      this.por,
      this.image,
      this.name,
      this.year,
      this.description,
      this.town,
      this.country,
      this.price,
      this.type);
}

final List<Property> properties = [
  Property(
    '1',
    'coupé',
    'Essence',
    'manuellle de 6 vitesses',
    '2019',
    '54000 kms',
    'jaune',
    'cuir noir',
    '5000 cm3',
    '8',
    '450 hp/450 ch',
    '36 cv fiscaux',
    '4 places',
    '2 portes',
    ['images/car7.jpg', 'images/car9.jpg', 'images/car10.jpg'],
    'Mercedes GL 450',
    'Annee 2019',
    'La Mercedes GLA 450 AMG 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
    'Munich',
    'Allemagne',
    '4000,000€',
    'Automatique',
  ),
  Property(
    '2',
    'coupé',
    'Essence',
    'manuellle de 6 vitesses',
    '2017',
    '54000 kms',
    'jaune',
    'cuir noir',
    '5000 cm3',
    '8',
    '450 hp/450 ch',
    '36 cv fiscaux',
    '4 places',
    '2 portes',
    ['images/car3.jpg', 'images/car9.jpg', 'images/car10.jpg'],
    'Toyota Tundra',
    'Annee 2017',
    'La Toyota Tundra 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
    'Munich',
    'Allemagne',
    '4200,000€',
    'Automatique',
  ),
  Property(
    '3',
    'coupé',
    'Essence',
    'manuellle de 6 vitesses',
    '2019',
    '54000 kms',
    'jaune',
    'cuir noir',
    '5000 cm3',
    '8',
    '450 hp/450 ch',
    '36 cv fiscaux',
    '4 places',
    '2 portes',
    ['images/car2.jpg', 'images/car9.jpg', 'images/car10.jpg'],
    'Mercedes GL 450',
    'Annee 2019',
    'La Mercedes GLA 450 AMG 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
    'Munich',
    'Allemagne',
    '4000,000€',
    'Automatique',
  ),
  Property(
    '4',
    'coupé',
    'Essence',
    'manuellle de 6 vitesses',
    '2019',
    '54000 kms',
    'jaune',
    'cuir noir',
    '5000 cm3',
    '8',
    '450 hp/450 ch',
    '36 cv fiscaux',
    '4 places',
    '2 portes',
    ['images/car4.jpg', 'images/car9.jpg', 'images/car10.jpg'],
    'Mercedes MI 450',
    'Annee 2019',
    'La Mercedes MI 450 AMG 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
    'Berlin',
    'Allemagne',
    '4000,000€',
    'Automatique',
  ),
  Property(
    '5',
    'coupé',
    'Essence',
    'manuellle de 6 vitesses',
    '2019',
    '54000 kms',
    'jaune',
    'cuir noir',
    '5000 cm3',
    '8',
    '450 hp/450 ch',
    '36 cv fiscaux',
    '4 places',
    '2 portes',
    ['images/car6.png', 'images/car9.jpg', 'images/car10.jpg'],
    'Mercedes GL 450',
    'Annee 2019',
    'La Mercedes GLA 450 AMG 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
    'Munich',
    'Allemagne',
    '4000,000€',
    'Automatique',
  ),
  Property(
    '6',
    'coupé',
    'Essence',
    'manuellle de 6 vitesses',
    '2019',
    '54000 kms',
    'jaune',
    'cuir noir',
    '5000 cm3',
    '8',
    '450 hp/450 ch',
    '36 cv fiscaux',
    '4 places',
    '2 portes',
    ['images/car8.jpg', 'images/car9.jpg', 'images/car10.jpg'],
    'Mercedes GL 450',
    'Annee 2019',
    'La Mercedes GLA 450 AMG 4MATIC 2016 est un veritable bolide de rallye déguisé pour la route.Je n\'exagère pas:ce super petit utilitaire est alimenté par le moteur à 4 cylindres de serie le plus puissant au monde.exception faite des hybrides.',
    'Munich',
    'Allemagne',
    '4000,000€',
    'Automatique',
  ),
];
